import { spawn } from 'node:child_process'
import { existsSync } from 'node:fs'
import { readdir, writeFile } from 'node:fs/promises'
import { join, parse } from 'node:path'

/**
 * Compresses every JPG/PNG in /public/textures to .ktx2 (UASTC for
 * non-color data, ETC1S for color) using @gltf-transform/cli via npx.
 * Output sits next to the source as `<name>.ktx2`. Idempotent — skips
 * if the .ktx2 already exists.
 *
 * Also emits src/scene/textureManifest.ts mapping each source filename
 * to the compressed alternative when present, so the texture loader
 * can prefer the compressed file at runtime without any filesystem
 * checks on the client.
 *
 * Falls back gracefully if @gltf-transform/cli isn't installed locally
 * — emits an empty manifest so the loader still resolves to the JPGs.
 */
async function main() {
  const dir = 'public/textures'
  const files = await readdir(dir)
  const candidates = files.filter((f) => /\.(jpg|jpeg|png)$/i.test(f))

  for (const file of candidates) {
    const { name } = parse(file)
    const src = join(dir, file)
    const dst = join(dir, `${name}.ktx2`)

    if (existsSync(dst)) {
      console.log(`skip (exists): ${dst}`)
      continue
    }

    // Color maps (day/night/clouds/stars) use ETC1S for size. Data maps
    // (normal/roughness) use UASTC for quality.
    const isData = /normal|roughness/i.test(name)
    const args = isData
      ? ['-y', '@gltf-transform/cli@latest', 'uastc', src, dst]
      : ['-y', '@gltf-transform/cli@latest', 'etc1s', src, dst]

    console.log(`compress: ${src} -> ${dst} (${isData ? 'UASTC' : 'ETC1S'})`)
    await runNpx(args)
  }

  // Build the manifest. Includes only files where the .ktx2 actually exists,
  // so a partial / failed compression run still produces a valid manifest
  // that the loader can use (falling back to JPGs for missing entries).
  const manifest: Record<string, string> = {}
  for (const file of candidates) {
    const { name } = parse(file)
    const ktx2 = join(dir, `${name}.ktx2`)
    if (existsSync(ktx2)) manifest[file] = `${name}.ktx2`
  }
  await writeFile(
    'src/scene/textureManifest.ts',
    `// Auto-generated by scripts/compress-textures.ts. Do not edit.\n` +
      `export const TEXTURE_MANIFEST: Record<string, string> = ${JSON.stringify(manifest, null, 2)}\n`,
  )
  console.log(`wrote src/scene/textureManifest.ts with ${Object.keys(manifest).length} entries`)
}

function runNpx(args: string[]) {
  return new Promise<void>((resolve) => {
    const child = spawn('npx', args, { stdio: 'inherit' })
    child.on('exit', (code) => {
      if (code !== 0) {
        console.warn(`compress-textures: skipped (non-zero exit ${code})`)
      }
      resolve()
    })
    child.on('error', (err) => {
      console.warn(`compress-textures: skipped (toolchain missing): ${err.message}`)
      resolve()
    })
  })
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
